services:
  - type: web
    name: tekupvault-api
    env: node
    region: frankfurt
    plan: starter
    buildCommand: pnpm install --frozen-lockfile --prod=false && pnpm build
    startCommand: node apps/vault-api/dist/index.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: LOG_LEVEL
        value: info
      - key: PORT
        value: 3000
      - key: API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: tekupvault-db
          property: connectionString
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_WEBHOOK_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false

  - type: worker
    name: tekupvault-worker
    env: node
    region: frankfurt
    plan: starter
    buildCommand: pnpm install --frozen-lockfile --prod=false && pnpm build
    startCommand: node apps/vault-worker/dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: LOG_LEVEL
        value: info
      - key: DATABASE_URL
        fromDatabase:
          name: tekupvault-db
          property: connectionString
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false

databases:
  - name: tekupvault-db
    region: frankfurt
    plan: starter
    databaseName: tekupvault
    user: tekupvault
